### ISSUE TITLE
mac操作

### ISSUE THREAD

**Issue by cycold** [icewaters/icewaters.github.io#64]
暂停正在更新的软件后，mac的launchpad会有一个软件更新状态条，同时里面的暂停更新图标会变灰，
上面会有暂停或者正在下载的文字提示。
当打开launchpad时，按住option就会出现小x图标，点击删除即可。（不会卸载掉原来的软件,　只会停止当前的更新）

显示当前finder的路径：
➜  ~  defaults write com.apple.finder _FXShowPosixPathInTitle -bool TRUE
➜  ~  killall Finder

恢复默认：
defaults delete com.apple.finder _FXShowPosixPathInTitle
killall Finder

在桌面打开Finder：command ＋ N即可

在安装完webstorm的vim插件后，软件提示：
<img width="401" alt="test" src="https://cloud.githubusercontent.com/assets/2446601/10073812/22acd978-62fe-11e5-9665-a621dcc328e7.png">

最初不知道`Repeating keys`重复按键代表什么，后面发现当重复按住“J”键时，只能往下一行。
这时才明白重复按键是mac osx 限制了按键的连续触发。
使用命令开启重复按键（反之关闭）：
`defaults write -g ApplePressAndHoldEnabled 0`
开启完后，需要重启软件

**Comment by icewaters** [comment]
Mac总的shell没有linux下的`tree`命令,
可以通过`brew install tree`安装
使用tree注意目录遍历层级.
`tree -L 1` 显示第一层

**Comment by icewaters** [comment]
压缩加密文件 
`zip -e a.zip b.txt`
解压zip压缩包文件
`unzip a.zip`

**Comment by icewaters** [comment]
比如要重复上次的命令ps,只要在前面加上!即可
`!ps`,`!cp`,`!ls`,....
在命令前面加上感叹号,表示获取这个命令最近执行时的参数列表

**Comment by icewaters** [comment]
Mac知道进程名,查看其占用的端口号:
获取进程pid:
`ps -ef | grep mongod`
 `lsof -Pn | grep pid`
查看

**Comment by icewaters** [comment]
查看系统支持的shell
`cat /etc/shells`
根据进程名(pname)获取pid,反之获取进程名
`ps -ef | grep pname` 
`ps aux | grep pname` 
`pgrep -lf pname`
通过端口号,查看其进程,port为端口,注意端口号前面一半有:
`lsof -i :port`
通过进程名杀死进程
`pkill pname` 
`killall pname`
使用!(感叹号)取回命令最近使用的参数
`!ps`
使修改的配置文件马上生效
`source configname`
